### ISSUE TITLE
Add option to import translation and script from storage

### ISSUE THREAD

**Issue by Gamer750** [Waqar144/quran_memorization_helper#6]
Add option to import translation and script (like uthmani ) from storage

**Comment by Gamer750** [comment]
Any update

**Comment by Waqar144** [comment]
I have started working on custom translation this week, will probably be part of next release inshaAllah.

If you would like to test it before release, I can share an apk here once I have something usable.

**Comment by Gamer750** [comment]
> I have started working on custom translation this week, will probably be part of next release inshaAllah.
> 
> If you would like to test it before release, I can share an apk here once I have something usable.

Bro don't make the app online. If we can import translation we like would have been better for privacy

**Comment by Waqar144** [comment]
Changing translation should be possible in the next release (1.2.2). You will have to download the translation from tanzil.net.
