### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Waqar144/quran_memorization_helper#7]
Did you forget to bump flutter submodule maybe?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6251746348#L1092

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/5f0b6be68ea563efe9c122d73cb36bda01c61f4d

**Comment by Waqar144** [comment]
yep. I bumped it 3.16.9 now and retagged `1.2.0`.

**Comment by Waqar144** [comment]
yep. I bumped it 3.16.9 now and retagged `1.2.0`.

**Comment by licaon-kter** [comment]
updated https://gitlab.com/fdroid/fdroiddata/-/commit/581aeecb07738d6f947353084da24d767608c351
