### ISSUE TITLE
Normal reading mode

### ISSUE THREAD

**Issue by Gamer750** [Waqar144/quran_memorization_helper#8]

**Comment by Waqar144** [comment]
What is this mode?

**Comment by Gamer750** [comment]
> What is this mode?

This is now 

https://github.com/Waqar144/quran_memorization_helper/assets/141329708/b650aa3b-0341-48f3-8573-fce5cd6abcdb

Can you change it like this

https://github.com/Waqar144/quran_memorization_helper/assets/141329708/f4ce7bde-3fd8-4478-bd7d-a1d6558fd409

I am not talking about things like dark mode . I am talking UI and when you click an ayah on this app it shows red things I know the apps main purpose Hafiz to memorize quran. Can you add option to show translation when clicking an ayah instead this red things

**Comment by Waqar144** [comment]
> Can you add option to show translation when clicking an ayah instead this red things

I added an option for this. Will be available in the next release.
